/* BASIC AUTH */
export const BASIC_AUTH_SIGNUP = "BASIC_AUTH_SIGNUP";
export const BASIC_AUTH_LOGIN = "BASIC_AUTH_LOGIN";
export const BASIC_AUTH_LOGOUT = "BASIC_AUTH_LOGOUT";
export const BASIC_AUTH_VERIFY_SESSION = "BASIC_AUTH_VERIFY_SESSION";
export const BASIC_AUTH_CONTROL_SESSION = "BASIC_AUTH_CONTROL_SESSION";
/* BASIC AUTH ERROR */
export const BASIC_AUTH_SIGNUP_ERROR = "BASIC_AUTH_SIGNUP_ERROR";
export const BASIC_AUTH_LOGIN_ERROR = "BASIC_AUTH_LOGIN_ERROR";
export const BASIC_AUTH_LOGOUT_ERROR = "BASIC_AUTH_LOGOUT_ERROR";
export const BASIC_AUTH_VERIFY_SESSION_ERROR =
  "BASIC_AUTH_VERIFY_SESSION_ERROR";

/* POST */
export const CREATE_NEW_POST = "CREATE_NEW_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const GET_ONE_POST = "GET_ONE_POST";
export const GET_ALL_POST = "GET_ALL_POST";

/* ERROR POST */
export const ERROR_CREATE_NEW_POST = "CREATE_NEW_POST";
export const ERROR_UPDATE_POST = "UPDATE_POST";
export const ERROR_DELETE_POST = "DELETE_POST";
export const ERROR_UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const ERROR_GET_ONE_POST = "GET_ONE_POST";
export const ERROR_GET_ALL_POST = "GET_ALL_POST";
