/* BASIC AUTH */
export const BASIC_AUTH_SIGNUP = "BASIC_AUTH_SIGNUP";
export const BASIC_AUTH_LOGIN = "BASIC_AUTH_LOGIN";
export const BASIC_AUTH_LOGOUT = "BASIC_AUTH_LOGOUT";
export const BASIC_AUTH_VERIFY_SESSION = "BASIC_AUTH_VERIFY_SESSION";
/* BASIC AUTH ERROR */
export const BASIC_AUTH_SIGNUP_ERROR = "BASIC_AUTH_SIGNUP_ERROR";
export const BASIC_AUTH_LOGIN_ERROR = "BASIC_AUTH_LOGIN_ERROR";
export const BASIC_AUTH_LOGOUT_ERROR = "BASIC_AUTH_LOGOUT_ERROR";
export const BASIC_AUTH_VERIFY_SESSION_ERROR =
  "BASIC_AUTH_VERIFY_SESSION_ERROR";
